### ISSUE TITLE
Нельзя поменять метадату при создании ВМ

### ISSUE THREAD

**Issue by Rid-lin** [yandex-cloud/yc-solution-library-for-security#35]
Тут указано https://github.com/yandex-cloud/yc-solution-library-for-security/tree/master/encrypt_and_keys/manage_secrets/windows-vm-secure-passwords#4-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-%D0%B2%D0%B8%D1%80%D1%82%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D1%83%D1%8E-%D0%BC%D0%B0%D1%88%D0%B8%D0%BD%D1%83 что можно включить скрипт инициализации метадаты, но этого сделать нельзя 
![изображение](https://github.com/yandex-cloud/yc-solution-library-for-security/assets/7646469/abbe8f06-020a-42c1-9e04-5e1af7d93691)
такого пункта просто нет

**Comment by nar3k** [comment]
@Sayanaro check it out please

**Comment by Sayanaro** [comment]
Это относится к Kosmos VM. Форма к ней привязана.
В вашем случае (принесенная винда) развертывание должно быть через yc cli

ЗЫж
Сегодня отправил PR с примером terraform.

**Comment by nar3k** [comment]
https://github.com/yandex-cloud/yc-solution-library-for-security/pull/36

**Comment by Sayanaro** [comment]
@Rid-lin проверил со своим образом - форма привязана к идентификатору продукта, а не к os-type. Поэтому развертывание в этом случае либо через yc cli, либо через террафомм (PR уже вмеджен в основную ветку)

Rid-lin
